### ISSUE TITLE
Is there a license for this code?

### ISSUE THREAD

**Issue by saintaardvark** [jmadinlab/surface_geometry#1]
Hi there -- thanks very kindly for publishing this.  I found the paper quite interesting.  However, I'm unsure what license you are using for this code.  

If I understand correctly, the paper (at least in the BioArxiv preprint) is licensed under [CC-BY-NC](http://creativecommons.org/licenses/by-nc/4.0/).  However, there's no LICENSE file in this repo, and  Creative Commons [recommends other licenses for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

Is this something you can clarify?

**Comment by jmadin** [comment]
@saintaardvark Sorry for the delay and thanks for bringing this up. I added the MIT license.
